version: '3'

services:
  app1:
    build: ./app1
    ports:
      - 5001:5000
    depends_on:
      - mongodb
    container_name: app1
  app2:
    build: ./app2
    ports:
      - 5002:5000
    depends_on:
      - mongodb
    container_name: app2
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
    container_name: nginx

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    container_name: mongodb
  
volumes:
  mongodb_data:


