version: '3'

services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    container_name: webapp

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    container_name: mongodb
  
volumes:
  mongodb_data:


