apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-challenge6-webnodb
  namespace: rbachelier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
        - name: webnodb-containers
          image: rabachelier21/flask-app:v1
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
