apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-challenge8
  namespace: rbachelier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb-containers
          image: rabachelier21/flask-app:v1
          env:
          - name: MONGODB_HOST
            value: mongodb-service
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              port: 8888
              path: /
            initialDelaySeconds: 30
            periodSeconds: 10
