apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: rbachelier
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort : 27017
  
