apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: rbachelier
spec:
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8888
  type: NodePort
